### ISSUE TITLE
Inline directive in MenuBackend.h makes setValue function not usable

### ISSUE THREAD

**Issue by zgoda** [WiringProject/Wiring#46]
https://github.com/WiringProject/Wiring/blob/master/framework/libraries/MenuBackend/MenuBackend.h#L435

This produces warning "inline function used but never defined", and then use of this function in code results in "undefined reference to 'MenuItem::setValue(int)'".

**Comment by AlexanderBrevig** [comment]
fixed by https://github.com/WiringProject/Wiring/commit/da0b6b9282ae6a3f047235b5a91b6df567fdf22f
thanks!
